name: Add Asset
on:
  workflow_dispatch:
    inputs:
      osmosis_zone:
        description: 'Osmosis Zone'
        required: true
        default: 'osmosis (osmosis-1)'
        options: 
          - 'osmosis (osmosis-1)'
          - 'osmosistestnet5 (osmo-test-5)'
          - 'osmosistestnet (osmo-test-4)'
      chain_name:
        description: 'chain_name (Chain Registry directory)'
        required: true
        default: 'cosmoshub'
      base_denom:
        description: 'base_denom (Asset base)'
        required: true
        default: 'uatom'
      path:
        description: 'path (IBC transfer path--required for all IBC transferred assets)'
        required: false
        default: 'transfer/channel-141/uatom'
      osmosis_main:
        description: 'osmosis_main (whether to appear as verified asset--default to FALSE)'
        required: false
        default: false
      override_symbol:
        description: 'Override Symbol (if different than registered)'
        required: false
      override_logo:
        description: 'Override Logo URL (if different than registered)'
        required: false
      override_cgid:
        description: 'Override CoinGecko ID (if different than registered)'
        required: false
      osmosis_pool:
        description: 'Liquidity added. Pool ID of any on-chain liquidity pool containing the asset'
        required: false
      request_staging_frontend:
        description: 'Liquidity not yet added. Request a Staging Frontend to add liquidity'
        required: false
        default: false

jobs:
  my-action-job:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      
      - name: Set environment variables
        run: |
          echo "osmosis_zone=${{ github.event.inputs.osmosis_zone }}" >> $GITHUB_ENV
          echo "chain_name=${{ github.event.inputs.chain_name }}" >> $GITHUB_ENV
          echo "base_denom=${{ github.event.inputs.base_denom }}" >> $GITHUB_ENV
          echo "path=${{ github.event.inputs.path }}" >> $GITHUB_ENV
          echo "osmosis_main=${{ github.event.inputs.osmosis_main }}" >> $GITHUB_ENV
          echo "override_symbol=${{ github.event.inputs.override_symbol }}" >> $GITHUB_ENV
          echo "override_logo=${{ github.event.inputs.override_logo }}" >> $GITHUB_ENV
          echo "override_cgid=${{ github.event.inputs.override_cgid }}" >> $GITHUB_ENV
          echo "osmosis_pool=${{ github.event.inputs.osmosis_pool }}" >> $GITHUB_ENV
          echo "request_staging_frontend=${{ github.event.inputs.request_staging_frontend }}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0

      - name: Run validation script
        run: node --experimental-modules -e "import { validate_add_asset() } from './validate_zone_data.mjs'; validate_add_asset();"
          
