on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Validate pools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Pools List schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./pools.schema.json
          json_path_pattern: .*pools.json$