on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Validate zone chains
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Zone Chains schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./zone_chains.schema.json
          json_path_pattern: .*zone_chains.json$
